---
# tasks file for ansible-role-logrotate

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create logrotate.d
  file:
    path: "{{ logrotate_conf_d }}"
    mode: 0755
    state: directory

- name: Create logrotate.conf
  template:
    src: logrotate.conf.j2
    dest: "{{ logrotate_config }}"

- name: Create PATH that includes /usr/local
  cron:
    name: PATH
    env: yes
    value: "/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"
  when: (ansible_os_family == 'FreeBSD') and (0 == 1) # disabled for now; env: yes was implemented in ansible 2.1

- name: Create a cron entry logrotate
  cron:
    name: logrotate
    minute: 0
    job: "/usr/bin/env PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin logrotate {{ logrotate_config }} >/dev/null"
  when: ansible_os_family == 'FreeBSD'
