---
- name: Install apt packages (if defined).
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ apt_packages | default([])  }}"
  when: apt_packages is defined

- name: Install pip packages (if defined).
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ pip_packages | default([])  }}"
  when: pip_packages is defined

- name: Install pip3 packages (if defined).
  pip:
    name: "{{ item }}"
    state: present
    executable: pip3                                                                                                                                                                                                                                            
  with_items: "{{ pip3_packages | default([])  }}"
  when: pip3_packages is defined

- name: Install npm packages (if defined).
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  with_items: "{{ npm_packages | default([]) }}"
  when: npm_packages is defined
