---
# tasks file for instance.print-hostkey
- name: If wipe_rc_local is defined, delete /etc/rc.local.
  file:
    path: /etc/rc.local
    state: absent
  when: wipe_rc_local is defined

- name: Touch /etc/rc.local file.
  file:
    path: /etc/rc.local
    mode: a+rx
    state: touch

- name: Add the ssh-keygen line.
  lineinfile:
    path: /etc/rc.local
    line: "#!/bin/sh"
    insertbefore: BOF

- name: Put the command to output the host SSH public key to the system log in /etc/rc.local.
  lineinfile:
    path: /etc/rc.local
    line: '/usr/bin/ssh-keygen -y -f /etc/ssh/ssh_host_ecdsa_key'

- name: Make the rc.local executable (just in case).
  shell:
    cmd: chmod a+x /etc/rc.local
