---
- name: Unhold / unpin Docker using apt-mark.
  shell:
    cmd: apt-mark unhold docker-ce
  changed_when: no

- name: Unhold / unpin Docker using aptitude.
  shell:
    cmd: aptitude -y unhold docker-ce
  changed_when: no

- name: Install Docker.
  apt:
    name: docker-ce
    state: latest
    update_cache: yes

- name: Pin Docker using apt-mark.
  shell:
    cmd: apt-mark hold docker-ce
  changed_when: no

- name: Pin Docker using aptitude.
  shell:
    cmd: aptitude -y hold docker-ce
  changed_when: no

