---
- name: Install bind9.
  apt:
    name: bind9
    state: present

- name: Template named.conf.options.
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options

- name: Template named.conf.local.
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local

- name: Template the zone.
  template:
    src: corp.bcrindustries.com.zone.j2
    dest: /etc/bind/corp.bcrindustries.com.zone

- name: Validate the config.
  shell:
    cmd: named-checkconf
  register: validate

- name: Debug.
  debug:
    msg: "{{ validate.stdout }}"

- name: If restart_bind is defined, restart the systemd service.
  service:
    name: bind9
    state: restarted
    enabled: yes
  when: restart_bind is defined

- name: Start the bind9 systemd service.
  service:
    name: bind9
    state: started
    enabled: yes
