---
- name: Debug static_site_docker_image.
  debug:
    msg: "{{ static_site_docker_image }}"

- name: Get hostname.
  shell:
    cmd: hostname
  register: myhost

- name: Debug hostname
  debug:
    msg: "{{ myhost.stdout }}"

- name: Make the static-site directory.
  file:
    path: "{{ volume_mount }}/static-site"
    state: directory

- name: Docker login.
  shell:
    cmd: $(aws --region {{ region }} ecr get-login --no-include-email)

- name: Pull Docker image.
  shell:
    cmd: docker pull {{ static_site_docker_image }}

- name: Template the static-site.service file
  template:
    src: static-site.service.j2
    dest: /etc/systemd/system/static-site.service

- name: Reload systemd.
  shell: systemctl daemon-reload

- name: Restart static-site when 'restart_static_site' is defined.
  service:
    name: static-site
    state: restarted
    enabled: yes
  when: restart_static_site is defined

- name: Start services.
  service:
    name: static-site
    state: started
    enabled: yes

