---
- name: Make the nginx-reverse-proxy directories.
  file:
    path: "{{ volume_mount }}/nginx-reverse-proxy/{{ item }}"
    state: directory
  with_items:
    - config

- name: Make the certbot directory.
  file:
    path: "{{ volume_mount }}/certbot"
    state: directory

- name: Pull nginx Docker image.
  shell:
    cmd: docker pull {{ nginx_docker_image }} | grep Status | tail -n 1
  register: docker_pull
  changed_when: docker_pull.stdout is not search('Image is up to date')

- name: When nginx_htpasswd is defined, Copy in the htpasswd file.
  copy: 
    content: "{{ nginx_htpasswd }}"
    dest: "{{ volume_mount }}/nginx-reverse-proxy/config/.htpasswd"
  when: nginx_htpasswd is defined

- name: Template the configuration file.
  template:
      dest: "{{ volume_mount }}/nginx-reverse-proxy/config/nginx-reverse-proxy.conf"
      src: "{{ nginx_reverse_proxy_config }}"

- name: Template the global SSL configuration.
  template:
      dest: "{{ volume_mount }}/nginx-reverse-proxy/config/ssl.conf"
      src: ssl.conf.j2
  when: ignore_ssl_conf is not defined

- name: Template the systemd unit file.
  template:
      dest: /etc/systemd/system/nginx-reverse-proxy.service
      src: nginx-reverse-proxy.service.j2

- name: Reload systemd unit file.
  command: systemctl daemon-reload
  changed_when: no

- name: Restart nginx-reverse-proxy when restart_nginx_reverse_proxy is defined.
  service:
    name: nginx-reverse-proxy
    state: restarted
  when: restart_nginx_reverse_proxy is defined

- name: Start nginx-reverse-proxy.
  service:
    name: nginx-reverse-proxy
    state: started
    enabled: yes
