---
- name: Create the certbot directory.
  file:
    path: "{{ volume_mount }}/certbot"
    state: directory

- name: Copy the zip file to the instances.
  copy:
    src: "{{ certbot_deploy_working_dir }}/{{ domain }}.zip"
    dest: "{{ volume_mount }}/certbot/{{ domain }}.zip"

- name: Unzip the file.
  shell:
    cmd: unzip -o ./{{ domain }}.zip
    chdir: "{{ volume_mount }}/certbot/"
  changed_when: no

- name: Get service status.
  service_facts:

- name: Debug nginx_service when it exists
  debug:
    msg: "{{ ansible_facts['services'][nginx_service]['state'] }}"
  when: nginx_service is defined and ansible_facts['services'][nginx_service] is defined

- name: Reload the {{ nginx_service }} service.
  service:
    name: "{{ nginx_service }}"
    state: reloaded
  changed_when: no
  when: nginx_service is defined and ansible_facts['services'][nginx_service] is defined


