---
- name: Debug facts.
  debug:
    msg: |
      certbot_s3_bucket: {{ certbot_s3_bucket }}
      certbot_s3_prefix: {{ certbot_s3_prefix }}
      certbot_deploy_working_dir: {{ certbot_deploy_working_dir }}
      domain: {{ domain }}
  delegate_to: 127.0.0.1
  run_once: true
  become: no

- name: Install unzip.
  apt:
    name: unzip
    state: present

- name: Delete the temporary workdir (make sure the slate is clean).
  file:
    path: "{{ certbot_deploy_working_dir }}"
    state: absent
  delegate_to: 127.0.0.1
  run_once: true
  become: no

- name: Make a temporary-certbot workdir, configdir, and logsdir.
  file:
    path: "{{ certbot_deploy_working_dir }}"
    state: directory
  changed_when: no
  delegate_to: 127.0.0.1
  run_once: true
  become: no

- name: Sync the S3 bucket.
  shell:
    cmd: aws s3 cp s3://{{ certbot_s3_bucket }}/{{ certbot_s3_prefix }}/{{ domain }}.zip ./{{ domain }}.zip
    chdir: "{{ certbot_deploy_working_dir }}"
  changed_when: no
  delegate_to: 127.0.0.1
  run_once: true
  become: no

