- hosts: all
  remote_user: "{{ user }}"
  vars:
    - new_hostname: bcrweb
    - http_port: 80
    - timezone: "America/New_York"
  gather_facts: true
  become: true
  roles:
    - role: nginxinc.nginx
    - role: chusiang.php7
    - role: arillso.motd
    - role: geerlingguy.firewall
    - role: oefenweb.fail2ban
    - role: softasap.sa-secure-audit-rkhunter
    - role: reallyenglish.logrotate    
    - role: GROG.reboot
  tasks:            
    - name: Copy ISSUE
      copy:
        src: resources/issue
        dest: /etc/issue
        owner: root
        group: root
        mode: 0644    




  post_tasks:
    - name: Enable shell_exec vulnerability in PHP
      ansible.builtin.lineinfile:
        path: /etc/php/7.1/fpm/php.ini
        regexp: '^disable_functions = exec'
        line: disable_functions = passthru,proc_open,popen 
    - name: Change FPM listen.owner
      ansible.builtin.lineinfile:
        path: /etc/php/7.1/fpm/pool.d/www.conf
        regexp: '^listen.owner ='
        line: listen.owner = nginx
    - name: Change FPM listen.group
      ansible.builtin.lineinfile:
        path: /etc/php/7.1/fpm/pool.d/www.conf
        regexp: '^listen.group ='
        line: listen.group = nginx           
    - name: Copy website to remote host
      copy:
        src: ../src/default/
        dest: /usr/share/nginx/html
        owner: root
        group: root
        mode: 0755
    - name: Copy explicit nginx + php configuration
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        owner: root
        group: root
        mode: 0644
    - name: Copy PHP Info file
      template:
        src: templates/info.php.j2
        dest: /usr/share/nginx/html/info.php
        owner: root
        group: root
        mode: 0644          
    - name: Restart Nginx service
      systemd:
        name: nginx
        state: restarted
        daemon_reload: yes                
    - name: Cleanup unused packages
      apt:
          autoremove: yes
    - name: change hostname
      hostname:
        name: "{{ new_hostname }}"
    - name: Update /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127.0.1.1'
        line: "127.0.1.1 {{ new_hostname }}"                 
    - name: reboot to finalize prep
      include_role:
          name: GROG.reboot
    
