- hosts: all
  gather_facts: true
  become: yes
  remote_user: "{{ user }}"  
  vars:
    - new_hostname: wordpress
    - mysql_root_password: password 
  roles:
    - role: bsmeding.webmin
    - role: arillso.motd    
    - role: robertdebock.roles.mysql
      mysql_databases:
        - name: wordpressdb
          encoding: utf8
          collation: utf8_bin
      mysql_users:
        - name: root
          password: password
          priv: "wordpressdb.*:ALL" 
    - role: turgon37.apache2
      apache2__modules_enabled_group:
        - access_compat # provide supports for old directives Allow,Order that are deprecated
        - alias  # provide  Alias
        - authn_core
        - authz_core
        - deflate # provide Gzip compression
        - dir # provide  DirectoryIndex
        - env  # provide SetEnv
        - headers  # provide RequestHeader
        - mime
        - mpm_prefork
        - negotiation # handle Content Type
        - php7.4
        - ssl  # Handle SSL
        - socache_shmcb  # required by mod_ssl    
  pre_tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
    - name: Install required packages
      apt:
        pkg:
        - curl 
        - mariadb-server
        - php7.4 
        - libapache2-mod-php7.4 
        - php-fpm 
        - php-curl 
        - php-gd 
        - php-mbstring 
        - php-xml 
        - php-xmlrpc 
        - php-soap 
        - php-intl 
        - php-zip 
        - php7.4-mysql
    - name: Copy Wordpress Source Backup
      ansible.builtin.copy:
        src: resources/wordpress-4-configured.tar.gz
        dest: /var/www/wordpress-4-configured.tar.gz
        owner: root
        group: root
        mode: 0644           
    - name: Copy Wordpress Database Backup
      ansible.builtin.copy:
        src: resources/wp-database-backup.2.1.1.zip
        dest: /home/sysadmin/wp-database-backup.2.1.1.zip
        owner: sysadmin
        group: sysadmin
        mode: 0644         
  tasks:
    - name: Copy ISSUE
      copy:
        src: resources/issue
        dest: /etc/issue
        owner: root
        group: root
        mode: 0644    
    - name: change hostname
      hostname:
        name: "{{ new_hostname }}"   
    - name: Update /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127.0.1.1'
        line: "127.0.1.1 {{ new_hostname }}"                  
    - name: Decompress Wordpress backup
      ansible.builtin.shell: 
        cmd: tar zxvf wordpress-4-configured.tar.gz
        chdir: /var/www  
  post_tasks:   
    - name: Copy Apache Site Configuration
      template:
        src: templates/wordpress-apache-site.conf.j2
        dest: /etc/apache2/sites-enabled/000-default.conf
        owner: root
        group: root
        mode: 0644
    - name: restart machine
      reboot:
