- hosts: all
  gather_facts: true
  become: yes
  remote_user: "{{ user }}"  
  vars:
    - new_hostname: alfresco
    - docker_dns_resolvers:
      - 8.8.8.8
      - 1.1.1.1
  roles:
    #- role: robertdebock.roles.docker
    - role: robertdebock.roles.docker_compose
    - role: bsmeding.webmin
    - role: arillso.motd    
  pre_tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
    - name: Install required packages
      apt:
        pkg:
        - python3-pip
        - python3-dev
        - net-tools
        - htop
        - git
    - name: Copy docker-compose
      template:
        src: resources/alfresco-docker-compose.yml
        dest: /home/sysadmin/docker-compose.yml
        owner: sysadmin
        group: sysadmin
        mode: 0644   
  tasks:
    - name: Copy ISSUE
      copy:
        src: resources/issue
        dest: /etc/issue
        owner: root
        group: root
        mode: 0644    
    - name: "Stand-up Alfresco Stack"
      docker_compose:
        project_src: '/home/sysadmin/'
        pull: yes
        state: 'present'
        restarted: yes     
    - name: Add sysadmin user to Docker group
      ansible.builtin.user:
        name: sysadmin
        group: docker      
    - name: change hostname
      hostname:
        name: "{{ new_hostname }}"
    - name: Update /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127.0.1.1'
        line: "127.0.1.1 {{ new_hostname }}"                    
    - name: restart machine
      reboot:
