- hosts: all
  gather_facts: true
  become: yes
  remote_user: "{{ user }}"  
  vars:
    - new_hostname: filesrv
    - samba_netbios_name: FILESRV
    - samba_server_string: 'Welcome to the BCR Industries File Server'
    - samba_workgroup: ENGINEERS
    - samba_global_include: global-include.conf

    - samba_load_homes: true
    - samba_load_printers: false
    - samba_create_varwww_symlinks: true

    - samba_log: /var/log/samba.log
    - samba_log_size: 60000
    - samba_log_level: '3 passdb:5 auth:10 winbind:2 '
    - samba_map_to_guest: Never
    - samba_users:
      - name: user1
        password: Password123!
      - name: user2
        password: Password123!
      - name: timemachine
        password: timemachine
    - samba_username_map:
      - from: 'User Two'
        to: user2
    - samba_shares_root: /opt/samba
    - samba_shares:
      - name: restrictedshare
      - name: privateshare
        comment: 'Only readable/writeable by user1'
        valid_users: user1
        write_list: user1
        group: users
        browseable: 'no'
      - name: protectedshare
        public: 'yes'
        comment: 'Public, but only writeable by user2'
        write_list: user2
        group: users
        browseable: 'yes'
        include_file: protectedshare-include.conf
      - name: publicshare
        comment: 'Public share, writeable by all members of group ‘users’'
        public: 'yes'
        write_list: +users
        group: users
        setype: public_content_t
        browseable: 'yes'
        guest_ok: 'yes'
      - name: guestshare
        comment: 'Share accessible for guests'
        guest_ok: 'yes'
        writable: 'yes'
        browseable: 'yes'
  roles:
    - role: bsmeding.webmin
    - role: bertvv.samba
    - role: arillso.motd    
  pre_tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
    - name: Install required packages
      apt:
        pkg:
        - python3-pip
        - python3-dev
        - net-tools
        - htop
        - git
    - name: Ensure share group "users" exists with correct gid
      ansible.builtin.group:
        name: users
        state: present
        gid: 1750   
    - name: Create share folder if it does not exist
      ansible.builtin.file:
        path: /opt/samba
        group: users        
        state: directory
        mode: '0755'             
    - name: Create users
      user:
        name: "{{ item }}"
        groups: users
        append: true
      with_items:
        - user1
        - user2
        - timemachine
        - guest           
  tasks:
    - name: Copy ISSUE
      copy:
        src: resources/issue
        dest: /etc/issue
        owner: root
        group: root
        mode: 0644    
    - name: change hostname
      hostname:
        name: "{{ new_hostname }}"
    - name: Update /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127.0.1.1'
        line: "127.0.1.1 {{ new_hostname }}"                   
    - name: restart machine
      reboot:
