- hosts: all
  gather_facts: true
  become: yes
  remote_user: "{{ user }}"  
  vars:
    - new_hostname: artifactory
  roles:
    - role: robertdebock.roles.bootstrap
    - role: robertdebock.roles.core_dependencies
    - role: robertdebock.roles.java
    - role: robertdebock.roles.artifactory
    - role: bsmeding.webmin
    - role: arillso.motd       
  tasks:
    - name: Copy ISSUE
      copy:
        src: resources/issue
        dest: /etc/issue
        owner: root
        group: root
        mode: 0644   
    - name: Add JFrog APT Key
      ansible.builtin.apt_key:
          url: https://releases.jfrog.io/artifactory/api/gpg/key/public 
          state: present
    - name: Add JFrog APT Source
      ansible.builtin.shell: echo "deb https://releases.jfrog.io/artifactory/jfrog-debs xenial contrib" | sudo tee -a /etc/apt/sources.list.d/jfrog;
      become: true   # Ensure that the highest permissions are used on the remote host                   
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
    - name: Install JFrog CLI
      apt:
        pkg:
        - jfrog-cli-v2        
    - name: change hostname
      hostname:
        name: "{{ new_hostname }}"   
    - name: Update /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127.0.1.1'
        line: "127.0.1.1 {{ new_hostname }}"             
    - name: restart machine
      reboot: