- hosts: all
  gather_facts: true
  become: yes
  remote_user: "{{ user }}"  
  vars:
    - new_hostname: foreman.bcrindustries.co
    - foreman_hostname: foreman.bcrindustries.co
    - adminusername: admin
    - adminpass: admin
  roles:
    - role: cloudalchemy.prometheus 
    - role: arillso.motd      
  pre_tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
    - name: Install required packages
      apt:
        pkg:
        - python3-pip
        - python3-dev
        - net-tools
        - htop
        - git  
        - wget
        - gpg 
        - ca-certificates
    - name: Download Puppet6
      get_url:
        url: https://apt.puppet.com/puppet6-release-buster.deb
        dest: /tmp/puppet6-release-buster.deb
        mode: '0440'    
    - name: Install local copy of Puppet
      apt:
        deb: /tmp/puppet6-release-buster.deb             
  tasks:
    - name: Copy ISSUE
      copy:
        src: resources/issue
        dest: /etc/issue
        owner: root
        group: root
        mode: 0644    
    - name: change hostname
      hostname:
        name: "{{ new_hostname }}"
    - name: Add exec repository into sources list
      ansible.builtin.shell: echo "deb http://deb.theforeman.org/ buster 3.0" | sudo tee /etc/apt/sources.list.d/foreman.list
      become: true   # Ensure that the highest permissions are used on the remote host
    - name: Add plugin repository into sources list
      ansible.builtin.shell: echo "deb http://deb.theforeman.org/ plugins 3.0" | sudo tee /etc/apt/sources.list.d/foremanp.list
      become: true   # Ensure that the highest permissions are used on the remote host  
    - name: Add Puppet signing key
      ansible.builtin.apt_key:
          url: https://deb.theforeman.org/pubkey.gpg 
          state: present   
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes  
    - name: Install foreman-installer
      apt:
        pkg:
        - foreman-installer
        - ruby-hammer-cli-foreman-discovery
    - name: Run foreman installer
      ansible.builtin.shell: "foreman-installer --foreman-initial-admin-username={{ adminusername }} --foreman-initial-admin-password={{ adminpass }}"
      become: true   # Ensure that the highest permissions are used on the remote host  
    - name: Enable foreman discovery
      ansible.builtin.shell: foreman-installer --enable-foreman-plugin-discovery
      become: true   # Ensure that the highest permissions are used on the remote host                                         
    - name: restart machine
      reboot:
