- hosts: all
  gather_facts: true
  become: yes
  remote_user: "{{ user }}"  
  vars:
    - new_hostname: ftpsrv
    - vsftpd_users:
        - username: ftpuser
          name: FTP User
          password: "{{ 'ftpuser' | password_hash('sha256', 'password') }}"
    - vsftpd_config:
        listen_port: 21
        local_enable: YES
        write_enable: YES
        chroot_local_user: YES
        xferlog_enable: YES
        log_ftp_protocol: YES
        allow_writeable_chroot: YES
  roles:
    - role: bsmeding.webmin
    - role: arillso.motd    
    - role: weareinteractive.vsftpd    
  pre_tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
    - name: Install required packages
      apt:
        pkg:
        - python3-pip
        - python3-dev
        - net-tools
        - htop
        - git         
  tasks:
    - name: Copy ISSUE
      copy:
        src: resources/issue
        dest: /etc/issue
        owner: root
        group: root
        mode: 0644    
    - name: change hostname
      hostname:
        name: "{{ new_hostname }}"
    - name: Update /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127.0.1.1'
        line: "127.0.1.1 {{ new_hostname }}"                    
    - name: restart machine
      reboot:
