version: '3.3'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:12
    restart: always    
    environment:
      - POSTGRESQL_USER=bitnami
      - POSTGRESQL_PASSWORD=bitnami
      - POSTGRESQL_DATABASE=filedetails     
    volumes:
      - 'postgresql_data:/bitnami'
    ports:
      - '0.0.0.0:5432:5432'     
  phppgadmin:
    image: docker.io/bitnami/phppgadmin:7
    restart: always
    ports:
      - '80:8080'
      - '443:8443'
    depends_on:
      - postgresql
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on: 
      - postgresql
    ports:
      - "53603:53603"
      - "8088:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root      
  traefik:
    container_name: traefik
    restart: always    
    image: "traefik:v2.2.8"
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --log.level=DEBUG
      - --certificatesresolvers.leresolver.acme.httpchallenge=true
      - --certificatesresolvers.leresolver.acme.email=your-email #Set your email address here, is for the generation of SSL certificates with Let's Encrypt. 
      - --certificatesresolvers.leresolver.acme.storage=./acme.json
      - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json"
    labels:
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
  portainer:
    image: portainer/portainer-ce:2.0.0
    restart: always
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      # Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`192.168.114.22`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=9000"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.routers.frontend.tls.certresolver=leresolver"
      
      # Edge
      - "traefik.http.routers.edge.rule=Host(`edge.yourdomain.com`)"
      - "traefik.http.routers.edge.entrypoints=websecure"
      - "traefik.http.services.edge.loadbalancer.server.port=8000"
      - "traefik.http.routers.edge.service=edge"
      - "traefik.http.routers.edge.tls.certresolver=leresolver"      
volumes:
  portainer_data:
  postgresql_data:
    driver: local
